<?php
$sync=[
    "ftp_serv"=>"127.0.0.1",
    "ftp_port"=>21,
    "ftp_user"=>"test",
    "ftp_pass"=>"123456",
    "ftp_pasv"=>0,
    "db_serv"=>"localhost",
    "db_port"=>3306,
    "db_name"=>"",
    "db_user"=>"",
    "db_pass"=>""
];
